server:
 port: 5000

spring:
 datasource:
 driver-class-name: com.mysql.jdbc.Driver
 url: jdbc:mysql://192.168.0.73:3306/test?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
 username: root
 password: DBGO@123

 jpa:
 hibernate:
 ddl-auto: update # 第一次简表create 后面用update
 show-sql: true