server:
  port: 8000

spring:
  application:
    name: java基础
#  zipkin:
##通过引入spring-cloud-starter-zipkin依赖和设置spring.zipkin.base-url就可以了。
#    base-url: http://localhost:9411
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/